apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mu876mq27-python 
  janus-idp.io/tekton: mu876mq27-python
  backstage.io/kubernetes-id: mu876mq27-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mu876mq27-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml