apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mu876mq27-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mu876mq27-python 
  name: mu876mq27-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mu876mq27-python 
